### ISSUE TITLE
TypeError: Object function Object() { [native code] } has no method 'assign'

### ISSUE THREAD

**Issue by sola97** [otakustay/danmaku-to-ass#11]
/usr/local/lib/node_modules/danmaku-to-ass/dist/bin/cli.js:64
        return value ? Object.assign(overrides, _defineProperty({}, name, conv
                              ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at /usr/local/lib/node_modules/danmaku-to-ass/dist/bin/cli.js:64:31
    at Array.reduce (native)
    at getConfigOverrides (/usr/local/lib/node_modules/danmaku-to-ass/dist/bin/cli.js:57:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/danmaku-to-ass/dist/bin/cli.js:91:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
我这是还有什么没装全吗？
部署命令
sudo apt-get install nodejs-legacy
sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
sudo apt-get install npm
npm install canvas
npm install -g danmaku-to-ass

**Comment by otakustay** [comment]
估计是Node版本不够新，能提供下你的版本吗，我想办法尽量把用新方法的地方改一下吧

**Comment by otakustay** [comment]
调整了一下代码，移除了对`Object.assign`、`Array.from`和`Array.prototype.fill`这三个函数的使用，麻烦再试一下行不行吧

``` shell
npm rm -g danmaku-to-ass
npm i -g danmaku-to-ass
```

最新版本是1.4.0

**Comment by sola97** [comment]
原来装的是 v0.10.25 更新到1.4.0还是无解，重装了个v4.4.7好了

**Comment by otakustay** [comment]
0.10也有点太老了……我会最低支持到v4以上
